version: '3.3'
services:
  caddy:
    container_name: caddy-server
    image: caddy:2.0.0-alpine
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./caddy_data:/data
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/ubuntu/.docker/config.json:/config.json
    command: watchtower api-server --interval 120
  api-server:
    container_name: api-server
    image: docker.pkg.github.com/nstranquist/idle-time-server/api:production
    restart: always
    depends_on:
      - caddy
    environment:
      - PORT=8080
      - API_SECRET=nodeRestApi
      - MONGO_DB_CONN=mongodb+srv://root:12wgfsB5S1UYJ970@idletime-cluster1.gk0uj.mongodb.net/production?retryWrites=true&w=majority
      - NODE_ENV=production
      
    ports:
      - 8080:8080
